## Инвентаризация файлов и изучения изначальной структуры

In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path(r"C:\temp\shift_ml\train_data")

files = []

for path in DATA_DIR.rglob("*"):
    if path.is_file():
        files.append(
            {
                "relative_path": str(path.relative_to(DATA_DIR)),
                "dataset_folder": path.parent.name,
                "file_name": path.name,
                "extension": path.suffix.lower(),
                "size_mb": round(path.stat().st_size / 1024**2, 3),
            }
        )

inventory = (
    pd.DataFrame(files)
    .sort_values(["dataset_folder", "file_name"])
    .reset_index(drop=True)
)

display(inventory)
display(
    inventory.groupby("extension", dropna=False)
    .agg(
        files=("file_name", "count"),
        total_size_mb=("size_mb", "sum"),
    )
    .sort_values("files", ascending=False)
)

inventory.to_csv(
    DATA_DIR / "data_files_inventory.csv",
    index=False,
    encoding="utf-8"
)

,relative_path,dataset_folder,file_name,extension,size_mb
0,dataset_1\data.csv,dataset_1,data.csv,.csv,0.038
1,dataset_10\data.csv,dataset_10,data.csv,.csv,0.210
2,dataset_11\data.csv,dataset_11,data.csv,.csv,0.205
3,dataset_12\data.csv,dataset_12,data.csv,.csv,0.200
4,dataset_13\data.parquet,dataset_13,data.parquet,.parquet,0.047
5,dataset_14\data.parquet,dataset_14,data.parquet,.parquet,0.046
6,dataset_15\data.csv,dataset_15,data.csv,.csv,0.202
7,dataset_16\data.parquet,dataset_16,data.parquet,.parquet,0.046
8,dataset_17\data.json,dataset_17,data.json,.json,1.532
9,dataset_18\data.parquet,dataset_18,data.parquet,.parquet,0.047
10,dataset_19\data.json,dataset_19,data.json,.json,1.610
11,dataset_2\data.csv,dataset_2,data.csv,.csv,0.204
12,dataset_20\data.xlsx,dataset_20,data.xlsx,.xlsx,0.117
13,dataset_21\data.csv,dataset_21,data.csv,.csv,0.198
14,dataset_22\data.parquet,dataset_22,data.parquet,.parquet,0.046
15,dataset_23\data.json,dataset_23,data.json,.json,1.634
16,dataset_24\data.xlsx,dataset_24,data.xlsx,.xlsx,0.122
17,dataset_25\data.xlsx,dataset_25,data.xlsx,.xlsx,0.116
18,dataset_26\data.parquet,dataset_26,data.parquet,.parquet,0.046
19,dataset_27\data.parquet,dataset_27,data.parquet,.parquet,0.048
20,dataset_28\data.xlsx,dataset_28,data.xlsx,.xlsx,0.119
21,dataset_29\data.csv,dataset_29,data.csv,.csv,0.208
22,dataset_3\data.xlsx,dataset_3,data.xlsx,.xlsx,0.118
23,dataset_30\data.csv,dataset_30,data.csv,.csv,0.222
24,dataset_31\data.json,dataset_31,data.json,.json,1.564
25,dataset_32\data.csv,dataset_32,data.csv,.csv,0.211
26,dataset_33\data.xlsx,dataset_33,data.xlsx,.xlsx,0.121
27,dataset_34\data.xlsx,dataset_34,data.xlsx,.xlsx,0.114
28,dataset_35\data.xlsx,dataset_35,data.xlsx,.xlsx,0.122
29,dataset_36\data.csv,dataset_36,data.csv,.csv,0.211
30,dataset_37\data.json,dataset_37,data.json,.json,1.510
31,dataset_38\data.csv,dataset_38,data.csv,.csv,0.202
32,dataset_39\data.json,dataset_39,data.json,.json,1.540
33,dataset_4\data.parquet,dataset_4,data.parquet,.parquet,0.047
34,dataset_40\data.csv,dataset_40,data.csv,.csv,0.214
35,dataset_41\data.xlsx,dataset_41,data.xlsx,.xlsx,0.114
36,dataset_42\data.xlsx,dataset_42,data.xlsx,.xlsx,0.108
37,dataset_43\data.parquet,dataset_43,data.parquet,.parquet,0.047
38,dataset_44\data.csv,dataset_44,data.csv,.csv,0.209
39,dataset_45\data.csv,dataset_45,data.csv,.csv,0.204
40,dataset_46\data.parquet,dataset_46,data.parquet,.parquet,0.046
41,dataset_47\data.xlsx,dataset_47,data.xlsx,.xlsx,0.116
42,dataset_48\data.csv,dataset_48,data.csv,.csv,0.201
43,dataset_5\data.parquet,dataset_5,data.parquet,.parquet,0.046
44,dataset_6\data.parquet,dataset_6,data.parquet,.parquet,0.046
45,dataset_7\data.csv,dataset_7,data.csv,.csv,0.214
46,dataset_8\data.csv,dataset_8,data.csv,.csv,0.209
47,dataset_9\data.json,dataset_9,data.json,.json,1.571
48,X_test_base.csv,train_data,X_test_base.csv,.csv,1.782
49,baseline_for_students.ipynb,train_data,baseline_for_students.ipynb,.ipynb,0.025
50,car_id_coverage.csv,train_data,car_id_coverage.csv,.csv,0.423
51,data_files_inventory.csv,train_data,data_files_inventory.csv,.csv,0.003
52,datasets_profile.csv,train_data,datasets_profile.csv,.csv,0.024
53,source_audit.csv,train_data,source_audit.csv,.csv,0.002
54,y_train_base.csv,train_data,y_train_base.csv,.csv,0.342

           files  total_size_mb
extension
.csv          24          6.138
.parquet      12          0.558
.xlsx         11          1.287
.json          7         10.961
.ipynb         1          0.025

# Анализ тестового набора данных и переменной Y

In [2]:
import pandas as pd

x_test_base = pd.read_csv(DATA_DIR / "X_test_base.csv")
y_train_base = pd.read_csv(DATA_DIR / "y_train_base.csv")

print("X_test_base shape:", x_test_base.shape)
display(x_test_base.head())
display(x_test_base.info())

print("\ny_train_base shape:", y_train_base.shape)
display(y_train_base.head())
display(y_train_base.info())
display(y_train_base.describe(include="all"))

pd.set_option('display.max_columns', None)

X_test_base shape: (8341, 22)

,car_id,Бренд,Год выпуска,Модель,Тип машины,Полное название,Исползование,КПП,Двигатель,Привод,...,Пробег,Цвет,Локация,Количество цилиндров,Тип кузова,Двери,Количество кресел,Оценка эксперта,Количество владельцев,Предложение
0,b2c2c5a9-6989-4596-bd8f-ce96c1720af9,SUBARU,2018.0,XV,SUV,2018 SUBARU XV 2.0I-L,USED,Automatic,"4 cyl, 2 L",AWD,...,44489,Grey / -,"MANDURAH, WA",4 cyl,SUV,4 Doors,5 Seats,4,3,Null
1,159a9504-c065-40a0-a47b-e97d4fd826b2,VOLKSWAGEN,2021.0,POLO,HATCHBACK,2021 VOLKSWAGEN POLO 70TSI TRENDLINE,USED,Automatic,"3 cyl, 1 L",Front,...,36612,White / Black,"WELSHPOOL, WA",3 cyl,HATCHBACK,5 Doors,5 Seats,2,7,NaN
2,4c7c09a0-5cea-43fa-bae0-8dd3207d8963,GWM,2022.0,HAVAL,SUV,2022 GWM HAVAL JOLION ULTRA HYBRID,USED,Automatic,"4 cyl, 1.5 L",Front,...,14651,Grey / Black,"MORLEY, WA",4 cyl,SUV,4 Doors,5 Seats,5,5,NaN
3,a2e7088a-3e5c-4811-86dc-543ff579970f,TOYOTA,2019.0,KLUGER,SUV,2019 TOYOTA KLUGER GRANDE (4X4),USED,Automatic,"6 cyl, 3.5 L",AWD,...,32493,Silver / Black Leather,"BERWICK, VIC",6 cyl,SUV,4 Doors,7 Seats,8,2,none
4,71648057-b854-4123-8fff-a3d85e9bab85,HYUNDAI,2019.0,KONA,SUV,2019 HYUNDAI KONA GO (FWD),USED,Automatic,"4 cyl, 2 L",Front,...,69436,White / -,"BUNGALOW, QLD",4 cyl,SUV,4 Doors,5 Seats,9,2,NaN

<class 'pandas.DataFrame'>
RangeIndex: 8341 entries, 0 to 8340
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   car_id                 8341 non-null   str
 1   Бренд                  8341 non-null   str
 2   Год выпуска            8341 non-null   float64
 3   Модель                 8341 non-null   str
 4   Тип машины             8328 non-null   str
 5   Полное название        8341 non-null   str
 6   Исползование           8341 non-null   str
 7   КПП                    8341 non-null   str
 8   Двигатель              8341 non-null   str
 9   Привод                 8341 non-null   str
 10  Топливо                8341 non-null   str
 11  Расход                 8341 non-null   str
 12  Пробег                 8341 non-null   str
 13  Цвет                   8341 non-null   str
 14  Локация                8105 non-null   str
 15  Количество цилиндров   8341 non-null   str
 16  Тип кузова             8195 non-null   str
 17  Двери                  7521 non-null   str
 18  Количество кресел      7467 non-null   str
 19  Оценка эксперта        8341 non-null   int64
 20  Количество владельцев  8341 non-null   int64
 21  Предложение            3329 non-null   str
dtypes: float64(1), int64(2), str(19)
memory usage: 2.9 MB

None

y_train_base shape: (8340, 2)

                                 car_id   Цена
0  099ec55b-6322-4a9f-8d5e-0bed830c3023  28777
1  25e3e231-5efc-4032-abe9-794c0cba8295  62999
2  54f3b009-8e37-49cd-905a-9637d6bf135c  28999
3  b361a8ff-af76-40cc-9f54-811b6bfd5eb5  33950
4  671c0cce-667a-4f44-87e7-fe999e17e55e  77888

<class 'pandas.DataFrame'>
RangeIndex: 8340 entries, 0 to 8339
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   car_id  8340 non-null   str
 1   Цена    8340 non-null   int64
dtypes: int64(1), str(1)
memory usage: 423.6 KB

None

                                      car_id          Цена
count                                   8340  8.340000e+03
unique                                  8340           NaN
top     099ec55b-6322-4a9f-8d5e-0bed830c3023           NaN
freq                                       1           NaN
mean                                     NaN  3.712697e+04
std                                      NaN  3.679723e+04
min                                      NaN  9.000000e+02
25%                                      NaN  1.944075e+04
50%                                      NaN  2.962000e+04
75%                                      NaN  4.399000e+04
max                                      NaN  1.500000e+06

## Что стало ясно

1. Все 48 dataset_* содержат по одному файлу, но форматы различаются: CSV, Parquet, Excel, JSON.

2. X_test_base.csv содержит 8 341 × 22.

3. y_train_base.csv содержит 8 340 строк, и car_id в нём уникален.

4. Целевая переменная в фактическом файле называется Цена.

5. В y_train_base нет пропусков в цене; минимальная цена — 900, то есть нулей нет. Однако для MAPE объекты с ценой 900 всё равно будут очень чувствительными: абсолютная ошибка на несколько тысяч даст огромный процент ошибки.

------------------------------------------------------------------------------------------------------------

## Подробное изучение файлов

In [3]:

def read_dataset(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()

    if suffix == ".csv":
        return pd.read_csv(path)

    if suffix == ".parquet":
        return pd.read_parquet(path)

    if suffix == ".xlsx":
        return pd.read_excel(path)

    if suffix == ".json":
        try:
            return pd.read_json(path)
        except ValueError:
            return pd.read_json(path, lines=True)

    raise ValueError(f"Неподдерживаемый формат: {suffix}")


profiles = []

for folder in sorted(DATA_DIR.glob("dataset_*")):
    files = list(folder.iterdir())

    if len(files) != 1:
        print(f"Проверить вручную: {folder.name}, файлов: {len(files)}")
        continue

    path = files[0]

    try:
        df = read_dataset(path)

        possible_keys = [
            col for col in df.columns
            if "id" in col.lower()
            or "car" in col.lower()
            or "vin" in col.lower()
        ]

        profiles.append(
            {
                "dataset": folder.name,
                "file": path.name,
                "format": path.suffix.lower(),
                "rows": df.shape[0],
                "columns_count": df.shape[1],
                "columns": " | ".join(map(str, df.columns)),
                "possible_keys": " | ".join(map(str, possible_keys)),
                "duplicate_rows": int(df.duplicated().sum()),
                "max_missing_pct": round(df.isna().mean().max() * 100, 2),
            }
        )

    except Exception as error:
        profiles.append(
            {
                "dataset": folder.name,
                "file": path.name,
                "format": path.suffix.lower(),
                "rows": None,
                "columns_count": None,
                "columns": None,
                "possible_keys": None,
                "duplicate_rows": None,
                "max_missing_pct": None,
                "error": repr(error),
            }
        )

datasets_profile = (
    pd.DataFrame(profiles)
    .sort_values("dataset")
    .reset_index(drop=True)
)

display(datasets_profile)

datasets_profile.to_csv(
    DATA_DIR / "datasets_profile.csv",
    index=False,
    encoding="utf-8-sig"
)

,dataset,file,format,rows,columns_count,columns,possible_keys,duplicate_rows,max_missing_pct
0,dataset_1,data.csv,.csv,174,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,0,10.34
1,dataset_10,data.csv,.csv,1069,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,423,21.89
2,dataset_11,data.csv,.csv,1047,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,396,22.64
3,dataset_12,data.csv,.csv,1014,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,369,20.91
4,dataset_13,data.parquet,.parquet,1109,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,451,23.81
5,dataset_14,data.parquet,.parquet,1039,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,412,25.51
6,dataset_15,data.csv,.csv,1028,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,391,24.22
7,dataset_16,data.parquet,.parquet,1056,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,411,23.67
8,dataset_17,data.json,.json,1057,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,383,18.45
9,dataset_18,data.parquet,.parquet,1069,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,425,24.98
10,dataset_19,data.json,.json,1110,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,468,23.69
11,dataset_2,data.csv,.csv,1026,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,399,20.08
12,dataset_20,data.xlsx,.xlsx,1062,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,409,19.40
13,dataset_21,data.csv,.csv,996,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,386,20.98
14,dataset_22,data.parquet,.parquet,987,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,368,25.03
15,dataset_23,data.json,.json,1128,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,446,25.44
16,dataset_24,data.xlsx,.xlsx,1096,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,405,24.27
17,dataset_25,data.xlsx,.xlsx,1034,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,399,24.08
18,dataset_26,data.parquet,.parquet,1053,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,414,22.41
19,dataset_27,data.parquet,.parquet,1103,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,457,20.04
20,dataset_28,data.xlsx,.xlsx,1067,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,415,24.84
21,dataset_29,data.csv,.csv,1063,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,422,25.49
22,dataset_3,data.xlsx,.xlsx,1056,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,392,20.55
23,dataset_30,data.csv,.csv,1108,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,416,21.21
24,dataset_31,data.json,.json,1079,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,435,21.32
25,dataset_32,data.csv,.csv,1073,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,426,22.27
26,dataset_33,data.xlsx,.xlsx,1096,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,475,24.73
27,dataset_34,data.xlsx,.xlsx,1022,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,394,23.68
28,dataset_35,data.xlsx,.xlsx,1105,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,428,20.81
29,dataset_36,data.csv,.csv,1062,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,419,20.24
30,dataset_37,data.json,.json,1042,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,382,22.94
31,dataset_38,data.csv,.csv,1023,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,410,22.19
32,dataset_39,data.json,.json,1062,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,402,23.26
33,dataset_4,data.parquet,.parquet,1076,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,411,24.44
34,dataset_40,data.csv,.csv,1071,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,433,19.33
35,dataset_41,data.xlsx,.xlsx,1025,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,379,22.44
36,dataset_42,data.xlsx,.xlsx,958,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,354,21.50
37,dataset_43,data.parquet,.parquet,1067,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,410,21.27
38,dataset_44,data.csv,.csv,1061,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,421,23.66
39,dataset_45,data.csv,.csv,1035,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,394,24.54
40,dataset_46,data.parquet,.parquet,1018,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,410,21.12
41,dataset_47,data.xlsx,.xlsx,1045,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,402,22.87
42,dataset_48,data.csv,.csv,1021,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,422,22.14
43,dataset_5,data.parquet,.parquet,993,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,383,23.87
44,dataset_6,data.parquet,.parquet,979,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,357,21.76
45,dataset_7,data.csv,.csv,1079,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,450,22.15
46,dataset_8,data.csv,.csv,1052,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,409,18.73
47,dataset_9,data.json,.json,1084,22,car_id | Бренд | Год выпуска | Модель | Тип ма...,car_id,430,20.20

Все показанные dataset_1–dataset_23 имеют одинаковую схему: 22 столбца и car_id. При этом внутри каждого набора очень много полных дубликатов строк: примерно 35–42%.

## Задача

48 источников с карточками автомобилей

→ часть машин повторяется между источниками

→ у записей могут различаться заполненность или качество полей

→ нужно собрать единую feature-таблицу по car_id

→ затем соединить train-автомобили с ценой по car_id

→ отдельно сформировать test-таблицу

# Риски и возможные ошибки
Нельзя делать concat(axis=1) между признаками и y_train_base: связь должна быть только через car_id.

Нельзя просто склеить 48 таблиц строками и обучаться на них: один и тот же автомобиль может попасть и в train, и в validation. Это даст утечку и искусственно хороший MAPE.

Если повторяющиеся записи имеют один car_id, на этапе валидации будем делить данные по автомобилям, а не по строкам.

In [4]:
X_base = pd.read_csv(DATA_DIR / "X_test_base.csv")
y_base = pd.read_csv(DATA_DIR / "y_train_base.csv")

X_base["car_id"] = X_base["car_id"].astype("string").str.strip()
y_base["car_id"] = y_base["car_id"].astype("string").str.strip()

x_ids = set(X_base["car_id"].dropna())
y_ids = set(y_base["car_id"].dropna())

def dataset_number(path: Path) -> int:
    return int(path.parent.name.split("_")[-1])


dataset_files = sorted(
    DATA_DIR.glob("dataset_*/data.*"),
    key=dataset_number
)

source_audit_rows = []
all_source_parts = []

for path in dataset_files:
    df = read_dataset(path).copy()
    source_name = path.parent.name

    if "car_id" not in df.columns:
        raise ValueError(f"В {source_name} нет car_id")

    df["car_id"] = df["car_id"].astype("string").str.strip()
    ids = set(df["car_id"].dropna())

    source_audit_rows.append(
        {
            "dataset": source_name,
            "rows": len(df),
            "unique_car_id": df["car_id"].nunique(),
            "duplicate_car_id_rows": int(
                df["car_id"].duplicated(keep=False).sum()
            ),
            "exact_duplicate_rows": int(df.duplicated().sum()),
            "unique_ids_in_y_train": len(ids & y_ids),
            "unique_ids_in_X_base": len(ids & x_ids),
            "unique_ids_unknown": len(ids - y_ids - x_ids),
            "same_schema_as_X_base": list(df.columns) == list(X_base.columns),
        }
    )

    all_source_parts.append(
        df[["car_id"]].assign(dataset=source_name)
    )

source_audit = pd.DataFrame(source_audit_rows)
display(source_audit)

all_source_ids = pd.concat(all_source_parts, ignore_index=True)

car_id_coverage = (
    all_source_ids
    .groupby("car_id", as_index=False)
    .agg(
        source_count=("dataset", "nunique"),
        total_rows_in_sources=("dataset", "size"),
    )
)

car_id_coverage["in_y_train"] = car_id_coverage["car_id"].isin(y_ids)
car_id_coverage["in_X_base"] = car_id_coverage["car_id"].isin(x_ids)

coverage_summary = (
    car_id_coverage
    .groupby(["in_y_train", "in_X_base"], dropna=False)
    .agg(
        unique_car_id=("car_id", "count"),
        mean_sources_per_car=("source_count", "mean"),
        max_sources_per_car=("source_count", "max"),
    )
    .reset_index()
)

print("Покрытие car_id во всех dataset_*:")
display(coverage_summary)

print("Сколько источников в среднем содержит один car_id:")
display(
    car_id_coverage["source_count"]
    .value_counts()
    .sort_index()
    .rename_axis("sources_per_car")
    .reset_index(name="car_id_count")
)

base_id_audit = pd.DataFrame(
    {
        "metric": [
            "Уникальных car_id в y_train_base",
            "Уникальных car_id в X_test_base",
            "Пересечение y_train_base и X_test_base",
            "Только в y_train_base",
            "Только в X_test_base",
        ],
        "value": [
            len(y_ids),
            len(x_ids),
            len(y_ids & x_ids),
            len(y_ids - x_ids),
            len(x_ids - y_ids),
        ],
    }
)

print("Связь y_train_base и X_test_base:")
display(base_id_audit)

source_audit.to_csv(
    DATA_DIR / "source_audit.csv",
    index=False,
    encoding="utf-8-sig",
)

car_id_coverage.to_csv(
    DATA_DIR / "car_id_coverage.csv",
    index=False,
    encoding="utf-8-sig",
)

,dataset,rows,unique_car_id,duplicate_car_id_rows,exact_duplicate_rows,unique_ids_in_y_train,unique_ids_in_X_base,unique_ids_unknown,same_schema_as_X_base
0,dataset_1,174,174,0,0,174,0,0,True
1,dataset_2,1026,174,1006,399,174,0,0,True
2,dataset_3,1056,174,1038,392,174,0,0,True
3,dataset_4,1076,174,1066,411,174,0,0,True
4,dataset_5,993,174,973,383,174,0,0,True
5,dataset_6,979,174,961,357,174,0,0,True
6,dataset_7,1079,174,1062,450,174,0,0,True
7,dataset_8,1052,174,1036,409,174,0,0,True
8,dataset_9,1084,174,1072,430,174,0,0,True
9,dataset_10,1069,174,1052,423,174,0,0,True
10,dataset_11,1047,174,1031,396,174,0,0,True
11,dataset_12,1014,174,995,369,174,0,0,True
12,dataset_13,1109,174,1097,451,174,0,0,True
13,dataset_14,1039,174,1025,412,174,0,0,True
14,dataset_15,1028,174,1013,391,174,0,0,True
15,dataset_16,1056,174,1042,411,174,0,0,True
16,dataset_17,1057,174,1052,383,174,0,0,True
17,dataset_18,1069,174,1054,425,174,0,0,True
18,dataset_19,1110,174,1099,468,174,0,0,True
19,dataset_20,1062,174,1042,409,174,0,0,True
20,dataset_21,996,174,974,386,174,0,0,True
21,dataset_22,987,174,971,368,174,0,0,True
22,dataset_23,1128,174,1120,446,174,0,0,True
23,dataset_24,1096,174,1087,405,174,0,0,True
24,dataset_25,1034,174,1025,399,174,0,0,True
25,dataset_26,1053,174,1040,414,174,0,0,True
26,dataset_27,1103,174,1089,457,174,0,0,True
27,dataset_28,1067,174,1051,415,174,0,0,True
28,dataset_29,1063,174,1049,422,174,0,0,True
29,dataset_30,1108,174,1093,416,174,0,0,True
30,dataset_31,1079,174,1065,435,174,0,0,True
31,dataset_32,1073,174,1059,426,174,0,0,True
32,dataset_33,1096,174,1078,475,174,0,0,True
33,dataset_34,1022,174,1004,394,174,0,0,True
34,dataset_35,1105,174,1094,428,174,0,0,True
35,dataset_36,1062,174,1047,419,174,0,0,True
36,dataset_37,1042,173,1026,382,173,0,0,True
37,dataset_38,1023,173,1006,410,173,0,0,True
38,dataset_39,1062,173,1052,402,173,0,0,True
39,dataset_40,1071,173,1054,433,173,0,0,True
40,dataset_41,1025,173,1005,379,173,0,0,True
41,dataset_42,958,173,937,354,173,0,0,True
42,dataset_43,1067,173,1051,410,173,0,0,True
43,dataset_44,1061,173,1051,421,173,0,0,True
44,dataset_45,1035,173,1019,394,173,0,0,True
45,dataset_46,1018,173,1000,410,173,0,0,True
46,dataset_47,1045,173,1034,402,173,0,0,True
47,dataset_48,1021,173,1006,422,173,0,0,True

Покрытие car_id во всех dataset_*:

,in_y_train,in_X_base,unique_car_id,mean_sources_per_car,max_sources_per_car
0,True,False,8340,1.0,1

Сколько источников в среднем содержит один car_id:

   sources_per_car  car_id_count
0                1          8340

Связь y_train_base и X_test_base:

                                   metric  value
0        Уникальных car_id в y_train_base   8340
1         Уникальных car_id в X_test_base   8341
2  Пересечение y_train_base и X_test_base      0
3                   Только в y_train_base   8340
4                    Только в X_test_base   8341

Нужно понять, чем отличаются строки одного car_id и можно ли безопасно собрать их в одну запись.

Этот код выберет несколько автомобилей из dataset_2, покажет все их строки и посчитает, в каких колонках есть конфликтующие значения.

In [5]:
dataset_2 = pd.read_csv(DATA_DIR / "dataset_2" / "data.csv")

print("Размер dataset_2:", dataset_2.shape)
print("Уникальных автомобилей:", dataset_2["car_id"].nunique())

cars_per_id = dataset_2["car_id"].value_counts()

print("\nРаспределение числа строк на один car_id:")
display(cars_per_id.describe())

sample_ids = cars_per_id.head(3).index.tolist()

for car_id in sample_ids:
    print(f"\n{'=' * 100}")
    print(f"car_id: {car_id}")
    print(f"Количество строк: {cars_per_id[car_id]}")
    
    car_rows = dataset_2.loc[dataset_2["car_id"] == car_id].copy()
    display(car_rows)

Размер dataset_2: (1026, 22)
Уникальных автомобилей: 174

Распределение числа строк на один car_id:

count    174.000000
mean       5.896552
std        3.243613
min        1.000000
25%        3.000000
50%        6.000000
75%        9.000000
max       11.000000
Name: count, dtype: float64

====================================================================================================
car_id: f4ca53ea-0df8-48d4-9326-5fcd934aa123
Количество строк: 11

,car_id,Бренд,Год выпуска,Модель,Тип машины,Полное название,Исползование,КПП,Двигатель,Привод,Топливо,Расход,Пробег,Цвет,Локация,Количество цилиндров,Тип кузова,Двери,Количество кресел,Оценка эксперта,Количество владельцев,Предложение
9,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
218,f4ca53ea-0df8-48d4-9326-5fcd934aa123,NaN,NaN,TRAX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN
219,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,NaN,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",NaN,WAGON,NaN,NaN,8.0,3.0,12074.0
220,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
221,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
222,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
223,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
224,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
225,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
226,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0
227,f4ca53ea-0df8-48d4-9326-5fcd934aa123,HOLDEN,2014.0,TRAX,3MT TRUE VALUE AUTO,2014 HOLDEN TRAX 2014 HOLDEN TRAX LS TJ AUTO MY14,USED,Automatic,-,Other,-,-,162892,Black / -,"VICTORIA PARK, WA",-,WAGON,NaN,NaN,8.0,3.0,12074.0

====================================================================================================
car_id: 88418cf3-9273-4950-8b13-c367a354db19
Количество строк: 11

,car_id,Бренд,Год выпуска,Модель,Тип машины,Полное название,Исползование,КПП,Двигатель,Привод,Топливо,Расход,Пробег,Цвет,Локация,Количество цилиндров,Тип кузова,Двери,Количество кресел,Оценка эксперта,Количество владельцев,Предложение
46,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
379,88418cf3-9273-4950-8b13-c367a354db19,NaN,2015.0,NaN,NaN,2015 JEEP CHEROKEE TRAILHAWK (4X4),NaN,NaN,"6 cyl, 3.2 L",NaN,NaN,10 L / 100 km,144089,NaN,NaN,NaN,NaN,4 Doors,NaN,NaN,NaN,NaN
380,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
381,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,NaN,5 Seats,8.0,5.0,20016.0
382,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,NaN,4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
383,88418cf3-9273-4950-8b13-c367a354db19,JEEP,NaN,CHEROKEE,SUV,NaN,USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,NaN,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
384,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,NaN,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
385,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
386,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
387,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0
388,88418cf3-9273-4950-8b13-c367a354db19,JEEP,2015.0,CHEROKEE,SUV,2015 JEEP CHEROKEE TRAILHAWK (4X4),USED,Automatic,"6 cyl, 3.2 L",4WD,UNLEADED,10 L / 100 km,144089,Silver / Black,"DUDLEY PARK, WA",6 cyl,SUV,4 Doors,5 Seats,8.0,5.0,20016.0

====================================================================================================
car_id: bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43
Количество строк: 11

,car_id,Бренд,Год выпуска,Модель,Тип машины,Полное название,Исползование,КПП,Двигатель,Привод,Топливо,Расход,Пробег,Цвет,Локация,Количество цилиндров,Тип кузова,Двери,Количество кресел,Оценка эксперта,Количество владельцев,Предложение
54,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
430,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,NaN,NaN,ALTO NORTH SHORE MG,NaN,NaN,NaN,NaN,NaN,HYBRID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 Seats,NaN,NaN,NaN
431,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,NaN,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
432,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,NaN,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,NaN,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,NaN,8.0,2.0,49495.0
433,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
434,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
435,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
436,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
437,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
438,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0
439,bd8bcee8-bb4f-41cf-beb6-b9a2b712bc43,MG,2022.0,HS,ALTO NORTH SHORE MG,2022 MG HS +EV PHEV EXCITE,NEW,Automatic,"4 cyl, 1.5 L",Front,HYBRID,1.7 L / 100 km,24,White / Knight Black,"ARTARMON, NSW",4 cyl,SUV,5 Doors,5 Seats,8.0,2.0,49495.0

Аудит конфликтов по всем датасетам:

In [ ]:
all_train_raw = []

for path in DATA_DIR.glob("dataset_*/data.*"):
    df = read_dataset(path).copy()
    df["source_dataset"] = path.parent.name
    all_train_raw.append(df)

train_raw = pd.concat(all_train_raw, ignore_index=True)

print("Размер сырых train-данных:", train_raw.shape)
print("Уникальных car_id:", train_raw["car_id"].nunique())

feature_columns = [
    col for col in train_raw.columns
    if col not in {"car_id", "source_dataset"}
]

conflict_report = []

for column in feature_columns:
    n_unique_values = (
        train_raw
        .groupby("car_id")[column]
        .nunique(dropna=True)
    )

    conflict_report.append(
        {
            "column": column,
            "cars_with_multiple_non_null_values": int((n_unique_values > 1).sum()),
            "share_of_cars_with_conflict_pct": round(
                (n_unique_values > 1).mean() * 100,
                2
            ),
            "max_unique_values_per_car": int(n_unique_values.max()),
        }
    )

conflict_report = (
    pd.DataFrame(conflict_report)
    .sort_values(
        "cars_with_multiple_non_null_values",
        ascending=False
    )
    .reset_index(drop=True)
)

display(conflict_report)

Размер сырых train-данных: (49679, 23)
Уникальных car_id: 8340

,column,cars_with_multiple_non_null_values,share_of_cars_with_conflict_pct,max_unique_values_per_car
0,Бренд,0,0.0,1
1,Год выпуска,0,0.0,1
2,Модель,0,0.0,1
3,Тип машины,0,0.0,1
4,Полное название,0,0.0,1
5,Исползование,0,0.0,1
6,КПП,0,0.0,1
7,Двигатель,0,0.0,1
8,Привод,0,0.0,1
9,Топливо,0,0.0,1
10,Расход,0,0.0,1
11,Пробег,0,0.0,1
12,Цвет,0,0.0,1
13,Локация,0,0.0,1
14,Количество цилиндров,0,0.0,1
15,Тип кузова,0,0.0,1
16,Двери,0,0.0,1
17,Количество кресел,0,0.0,1
18,Оценка эксперта,0,0.0,1
19,Количество владельцев,0,0.0,1
20,Предложение,0,0.0,1

# Итого выводы по структуре

Внутри каждого dataset_* один и тот же car_id встречается от 1 до 11 раз.

Повторные строки не содержат конфликтующих значений: для каждого признака у одного автомобиля максимум одно различное непустое значение.

Различия между строками — это в основном частично скрытые / пропущенные поля и полные дубликаты.

После объединения всех источников есть 49 679 сырых строк, но ровно 8 340 уникальных автомобилей — столько же, сколько строк в y_train_base.csv.

# Что это означает для задачи

Нужно собрать для каждого car_id одну каноническую строку:

несколько частично заполненных записей одного автомобиля

→ взять единственное доступное непустое значение по каждому полю

→ одна полная карточка автомобиля

Предложение выглядит подозрительно. В примерах это числовое значение, очень похожее на стоимость объявления. Это не обязательно leakage: если признак есть и в test, он может быть честно доступен на момент прогнозирования. Но нужно отдельно проверить:

насколько часто Предложение совпадает с Цена;

насколько оно коррелирует с целевой переменной;

не является ли это фактически целевой переменной под другим именем.

До проверки не будем ни удалять его, ни считать безопасным.